apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app: {{ include "app.name" . }}
  ports:
    - name: http
      port: {{ required "service.port is required" .Values.service.port }}
      targetPort: {{ required "service.port is required" .Values.service.port }}
